language: ruby
cache: bundler
rvm:
- 2.3.1
before_script: gem install jekyll
script: bundle exec jekyll build

branches:
  only:
    - master

exclude: [vendor]
sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: _site
  repo: alexis-hassler/alexis-hassler.github.io
  target_branch: master
  fqdn: blog.alexis-hassler.com