title: Bojo Blog
subtitle: Dev & Ops en Beaujolais
email: bojb@sewatech.fr
description:  > # this means to ignore newlines until "baseurl:"
    <p>J'ai créé la société <b>Sewatech</b> en 2005, pour y exercer mon métier de développeur <i title="ie. je fais du Java et de l'Angular">full stack</i>, à dominante <i title="ie. je suis meilleur en Spring qu'en CSS">back end</i>.</p>
    <p>Vous pouvez me <a href="https://www.sewatech.fr/contacts.html">contacter</a> si vous cherchez un développeur indépendant expérimenté (plus de 25 ans d'expérience) pour intégrer votre équipe de projet.
    Je peux aussi intervenir pour un audit ou une mission de conseil.</p>
    <p>Enfin, je donne des formations sur <a href="https://www.sewatech.fr/formation-spring.html">Spring</a>, <a href="https://www.sewatech.fr/formation-vertx.html">Vert.x</a>, <a href="https://www.sewatech.fr/formation-wildfly.html">WildFly</a>,... en intra sur site ou à distance</p>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.alexis-hassler.com/"
author: Alexis Hassler
twitter_username: AlexisHassler
github_username:  hasalex

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-asciidoc

encoding: UTF-8
lang: fr
date_format: "%-d %b %Y"
excerpt_separator: <!--more-->

paginate: 5

links:
  - title: "JTips, mon wiki"
    url: "https://www.jtips.info/Accueil"
    logo: "jtips.svg"
  - title: "Sewatech, mon entreprise"
    url: "https://www.sewatech.fr"
    logo: "sw.svg"
  - title: "Mon compte Twitter"
    url: "https://twitter.com/AlexisHassler"
    logo: "twitter.svg"
  - title: "Mon compte LinkedIn"
    url: "https://www.linkedin.com/in/hassler/"
    logo: "linkedin.svg"
  - title: "Mon compte GitLab"
    url: "https://gitlab.com/hasalex"
    logo: "gitlab.svg"
  - title: "Mon compte GitHub"
    url: "https://github.com/hasalex"
    logo: "github.svg"

asciidoctor:
  attributes:
  - icons=font
exclude:
- Makefile
- README.md
- LICENSE.txt
- Gemfile
- Gemfile.lock
- .ci
port: 4005
