# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bojo Blog
subtitle: Dev & Ops en Beaujolais
email: bojb@sewatech.fr
description:  > # this means to ignore newlines until "baseurl:"
    J'ai créé la société Sewatech en 2005, pour y exercer mon métier de conseil et de formation en informatique. Je suis spécialisé dans les technologies Java (développement et administration de serveurs d'applications).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.alexis-hassler.com/"
author: Alexis Hassler
twitter_username: AlexisHassler
github_username:  hasalex

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-asciidoc

encoding: UTF-8
lang: fr
date_format: "%-d %b %Y"
excerpt_separator: <!--more-->

paginate: 5

links:
  - title: "JTips, mon wiki"
    url: "https://jtips.info"
  - title: "Sewatech, mon entreprise"
    url: "https://sewatech.fr"



asciidoctor:
  attributes:
  - icons=font

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
