name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 'ruby-2.7.8' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec jekyll build --destination ../site/
    - run: cd ../site/ && git init
    - uses: actions-js/push@master
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        repository: alexis-hassler/alexis-hassler.github.io
        branch: master
        force: true
        directory: ../site
